/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM.
    id("org.jetbrains.kotlin.jvm").version("1.6.10")
}

repositories {
    mavenCentral()
}

dependencies {
    // Here's where the X509 Certificate Lookup SPI is defined
    implementation("org.keycloak:keycloak-services:17.0.0")

    // And this is needed by all SPIs
    implementation("org.keycloak:keycloak-server-spi:17.0.0")

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib")
}

tasks.wrapper {
    gradleVersion = "7.4.1"
}
